/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   get_stack.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: maaugust <maaugust@student.42porto.com>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/03/21 00:51:02 by maaugust          #+#    #+#             */
/*   Updated: 2026/03/21 15:23:59 by maaugust         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "push_swap.h"

/**
 * @fn static void free_words(char **words)
 * @brief Frees a null-terminated array of strings.
 * @details Iterates through a 2D char array (like one generated by ft_split) 
 * and frees each individual string, then frees the main array pointer.
 * @param words The null-terminated array of strings to free.
 */
static void	free_words(char **words)
{
	int	i;

	i = 0;
	if (!words)
		return ;
	while (words[i])
		free(words[i++]);
	free(words);
}

/**
 * @fn static t_stack *build_stack(char **words)
 * @brief Constructs the initial stack from an array of strings.
 * @details Allocates memory for each string, converts it to an integer, and 
 * adds it to a linked list. Clears the stack and returns NULL if an allocation 
 * fails.
 * @param words A null-terminated array of string values.
 * @return      A pointer to the newly created stack, or NULL on failure.
 */
static t_stack	*build_stack(char **words)
{
	t_stack	*stack;
	t_stack	*new;
	int		i;

	stack = NULL;
	i = -1;
	while (words[++i])
	{
		new = (t_stack *)ft_calloc(1, sizeof(t_stack));
		if (!new)
		{
			ft_stackclear(&stack);
			return (NULL);
		}
		new->val = (int)ft_atol(words[i]);
		new->idx = i;
		new->lis = false;
		new->next = NULL;
		ft_stackadd_back(&stack, new);
	}
	return (stack);
}

/**
 * @fn t_stack *get_stack(int argc, char **argv)
 * @brief Parses arguments and generates the stack.
 * @details Handles both single-string inputs (requiring splitting) and 
 * multi-argument inputs. Validates the input and delegates the stack building 
 * process.
 * @param argc The argument count.
 * @param argv The argument vector.
 * @return     A pointer to the validated and populated stack.
 */
t_stack	*get_stack(int argc, char **argv)
{
	char	**words;
	t_stack	*stack;
	bool	is_allocated;

	is_allocated = false;
	if (argc == 2)
	{
		words = ft_split(argv[1], ' ');
		is_allocated = true;
	}
	else
		words = argv + 1;
	if (!words || !words[0] || !validation(words))
	{
		if (is_allocated && words)
			free_words(words);
		print_error();
	}
	stack = build_stack(words);
	if (is_allocated)
		free_words(words);
	if (!stack)
		print_error();
	return (stack);
}
